---
- name: Install PostgreSQL
  apt:
    name: postgresql
    update_cache: yes
    state: latest

- name: Create a PostgreSQL user
  postgresql_user:
    db: postgres
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    login_user: postgres
    login_password: "{{ postgres_password }}"
    encrypted: yes

- name: Create a PostgreSQL database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    login_user: postgres
    login_password: "{{ postgres_password }}"
    state: present
