---
- name: Install dependencies
  apt:
    name: ['curl', 'git', 'build-essential', 'erlang', 'elixir', 'postgresql-client']
    update_cache: yes
    state: latest

- name: Install Hex package manager
  command: mix local.hex --force

- name: Install Phoenix framework
  command: mix archive.install hex phx_new --force

- name: Clone the repository
  git:
    repo: https://github.com/camberlucian/ansible_pd.git
    dest: /opt/app
    clone: yes
    update: yes

- name: Install app dependencies
  command: mix deps.get

- name: Create and migrate the database
  command: mix ecto.create && mix ecto.migrate

- name: Compile the app
  command: mix compile

- name: Start the Phoenix app
  command: mix phx.server
