---
- name: disable ipv6 all
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present
  become: yes

- name: disable ipv6 default
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present
  become: yes

- name: disable ipv6 loopback
  ansible.posix.sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: '1'
    state: present
  become: yes

- name: Run the equivalent of "apt-get update"
  ansible.builtin.apt:
    update_cache: yes
  become: yes
