- hosts: webservers
  become: true
  vars:
    app_name: AnsiblePhoenix
    app_path: /var/www/{{ app_name }}
    app_git_repo: git://github.com/camberlucian/ansible_pd.git
    app_env_vars:
      MIX_ENV: prod
      SECRET_KEY_BASE: abcdef123456
      DATABASE_URL: ecto://postgres:postgres@localhost/ansible_phoenix_dev
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Clone app repository
      git:
        repo: "{{ app_git_repo }}"
        dest: "{{ app_path }}"
        version: master

    - name: Install dependencies
      command: mix deps.get
      args:
        chdir: "{{ app_path }}"

    - name: Compile application
      command: mix compile
      args:
        chdir: "{{ app_path }}"

    - name: Create database
      command: mix ecto.create
      args:
        chdir: "{{ app_path }}"

    - name: Migrate database
      command: mix ecto.migrate
      args:
        chdir: "{{ app_path }}"

    - name: Start Phoenix app
      command: mix phx.server
      args:
        chdir: "{{ app_path }}"
      environment:
        "{{ app_env_vars }}"
